### ISSUE TITLE
Create a github project

### ISSUE THREAD

**Issue by BenRGH** [DoctorDib/BikeTheft#2]
Personally I'd go for automated kaban with reviews

**Comment by DoctorDib** [comment]
Just to make this clear, we need to decide whether or not we want to create issue / project tracking on either "Issues" or "Projects"

**Comment by BenRGH** [comment]
I figured we'd use Projects for creating and tracking tasks, Issues for triaging bugs/defects as we discover them

**Comment by DoctorDib** [comment]
Valid point, what do you think @MidgetJake

**Comment by Yakitrak** [comment]
I agree with @BenRGH , Issues makes sense to be for bug tracking and Projects to managing tasks.

**Comment by DoctorDib** [comment]
> automated kaban with reviews

I think it would be best to do "Automated Kaban" instead of "Automated Kaban with review"

**Comment by BenRGH** [comment]
I suggested the **with review** one just because it has triggers for PR's and that might be useful eventually, not super important though

**Comment by DoctorDib** [comment]
Does **with review** require a peer approval?

**Comment by BenRGH** [comment]
If it does then you can just disable it

**Comment by DoctorDib** [comment]
Ahh okay, as long as you can disable

**Comment by DoctorDib** [comment]
Project has been created
