### ISSUE TITLE
Setting up a database

### ISSUE THREAD

**Issue by DoctorDib** [DoctorDib/BikeTheft#5]
Just a proposal. We could go with MongoDB. Atlas provides free solution which I have used a few times. 

- Prefer Mongo as we are using JSON
- Better to use cloud solution over local 

https://www.mongodb.com/cloud/atlas

I got an account and am happy to set us up on Atlas and create schemas using mongoose on the backend if we go this route.

_Originally posted by @Yakitrak in https://github.com/DoctorDib/BikeTheft/issues/3#issuecomment-697329159_

**Comment by DoctorDib** [comment]
### Current Schema plan

**Users Table:**
![image](https://user-images.githubusercontent.com/14931616/94045392-4e2b4800-fdc7-11ea-8a5b-eccaad530f14.png)

**Bikes Table:**
![image](https://user-images.githubusercontent.com/14931616/94045253-1fad6d00-fdc7-11ea-82f4-0e178f9366b3.png)

**Forum Table:**
![image](https://user-images.githubusercontent.com/14931616/94045289-2c31c580-fdc7-11ea-909f-3e874f7a6fbe.png)

**Comment by DoctorDib** [comment]
@MidgetJake has made a valid point, his comment is as follows:

> Reasons why I am very much for postgres and not mongo:
> 
>     relational
>     performance
>     free tier on aws and super much easier to integrate with lambda.
>     using postgres I can do API work within the database itself instead of the functions. Which is both more performant and saves costs
> 
> Also:
> 
>     can handle JSON easily, no limitations
>     using multiple services for a backend slows latency down.

Comment found at #3

**Comment by BenRGH** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [github test](https://trello.com/c/VLWvOLjI/6-github-test)

**Comment by BenRGH** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set up database](https://trello.com/c/fBoTInzG/11-set-up-database)

**Comment by DoctorDib** [comment]
Postgres has now been setup and added to master
